version: '3.8'

services:
  doctorhub-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doctorhub-app
    image: doctorhub-backend:latest
    restart: always
    ports:
      - "9191:9091"  # Spring Boot → host:container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://doctorhub-db:5432/doctorhub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: production
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKETNAME: certificate
      JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    depends_on:
      - doctorhub-db
      - minio
    volumes:
      - ./logs:/app/logs
    networks:
      - doctorhub-network
    security_opt:
      - no-new-privileges:true

  doctorhub-db:
    image: postgres:16-alpine
    container_name: doctorhub-db
    restart: always
    ports:
      - "5543:5432"  # DB port → host:container
    environment:
      POSTGRES_DB: doctorhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - doctorhub_data:/var/lib/postgresql/data
    networks:
      - doctorhub-network
    security_opt:
      - no-new-privileges:true

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server --console-address ":9001" /data
    ports:
      - "9100:9000"  # MinIO API
      - "9101:9001"  # MinIO Console (UI)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    networks:
      - doctorhub-network
    security_opt:
      - no-new-privileges:true

volumes:
  doctorhub_data:
  minio_data:

networks:
  doctorhub-network:
    driver: bridge
