spring.application.name=demo

# App port
server.port=9091
#doctorhub-db
#localhost
spring.datasource.url=jdbc:postgresql://doctorhub-db:5432/doctorhub
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false



# Consider using HTTPS for the MinIO endpoint in production
# Example for env var: minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.endpoint=http://82.202.131.45:9100
# Configure using environment variable MINIO_ACCESS_KEY or other externalized configuration
# minio.access-key=minioadmin
minio.access-key=${MINIO_ACCESS_KEY:}
# Configure using environment variable MINIO_SECRET_KEY or other externalized configuration
# minio.secret-key=minioadmin
minio.secret-key=${MINIO_SECRET_KEY:}
minio.bucket-name=certificate

# Current multipart file size limits are very large (10GB).
# Review and adjust these values to appropriate limits based on your application's specific requirements
# to prevent potential abuse or performance issues.
spring.servlet.multipart.max-file-size= 10000MB
spring.servlet.multipart.max-request-size= 10000MB

server.max-http-request-header-size= 16KB


# Email konfiguratsiyasi
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=palankasovbirnarsa@gmail.com
spring.mail.password=d r x a e f p j j s t r d u t i

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
