package com.example.demo.exception;

import java.util.Arrays; // Added this import

// No specific @ResponseStatus here, as the GlobalExceptionHandler will set it
public class ResourceNotFoundException extends RuntimeException {

    private final String errorKey;
    private final Object[] args;

    public ResourceNotFoundException() {
        super("error.resource.not.found"); // Use the specific key for the super constructor as well
        this.errorKey = "error.resource.not.found"; // Default specific key
        this.args = new Object[0];
    }

    public ResourceNotFoundException(String errorKey) {
        super(errorKey); // The message for super() is mainly for logging if not caught by GlobalExceptionHandler
        this.errorKey = errorKey;
        this.args = new Object[0];
    }

    public ResourceNotFoundException(String errorKey, Object... args) {
        // Construct a simple message for super() for logging/debugging purposes.
        // The actual user-facing message will be generated by MessageSource.
        super(errorKey + (args != null && args.length > 0 ? " with args " + Arrays.toString(args) : ""));
        this.errorKey = errorKey;
        this.args = args;
    }

    public String getErrorKey() {
        return errorKey;
    }

    public Object[] getArgs() {
        return args;
    }
}